pipelines:
  branches:
    9.x-dev:
        - step:
              name: Install PHP dependencies
              image: drud/ddev-webserver:latest
              caches:
                - composer
              script:
                - composer install
              artifacts:
                - vendor/*
        - step:
            name: Build and Install
            image: node:10.15.3
            caches:
              - node
            script:
              - git fetch
              - git checkout -b 9.x
              - git merge $BITBUCKET_COMMIT
              - npm install
              - npm run build
              - ./Build/Scripts/cleanUp.sh
              - git push -v --tags origin 9.x:9.x
