pipelines:
  branches:
    9.x-dev:
        - step:
              name: Install PHP dependencies
              image: php:7.4
              caches:
                - composer
              script:
                - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
                - php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
                - php composer-setup.php
                - php -r "unlink('composer-setup.php');"
                - composer install
              artifacts:
                - vendor/*
        - step:
            name: Build and Install
            image: node:10.15.3
            caches:
              - node
            script:
              - git fetch
              - git checkout -b 9.x
              - git merge $BITBUCKET_COMMIT
              - npm install
              - npm run build
              - ./Build/Scripts/cleanUp.sh
              - git push -v --tags origin 9.x:9.x
