services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Blueways\BwBookingmanager\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Blueways\BwBookingmanager\Controller\BackendController:
    public: true

  Blueways\BwBookingmanager\Utility\FullCalendarUtility:
    public: true

  Blueways\BwBookingmanager\Command\TimeslotUpdateCommand:
    tags:
      - name: 'console.command'
        command: 'bookingmanager:timeslotUpdate'
        schedulable: false
