rootPageId: 1
base: /
baseVariants: {  }
languages:
  - title: English
    enabled: true
    languageId: '0'
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: ab
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: global
errorHandling: {  }
routes: {  }
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: ''
    map:
      '.json': 1556190329
      '.ics': 1556190330
  BookingManagerIcs:
    type: Extbase
    extension: BwBookingmanager
    plugin: Ics
    routes:
      - routePath: '/ics/{ics}'
        _controller: 'Ics::show'
        _arguments:
          - ics: ics
  BookingManagerApi:
    type: Extbase
    extension: BwBookingmanager
    plugin: Api
    routes:
      - routePath: '/api/calendar'
        _controller: 'Api::calendarList'
      - routePath: '/api/calendar/{calendar}'
        _controller: 'Api::calendarShow'
        _arguments:
          - calendar: calendar
      - routePath: '/api/calendar/{calendar}/{day}-{month}-{year}'
        _controller: 'Api::calendarShowDate'
        _arguments:
          - calendar: calendar
          - day: day
          - month: month
          - year: year
      - routePath: '/api/booking'
        _controller: 'Api::entryCreate'
      - routePath: '/api/login'
        _controller: 'Api::login'
      - routePath: '/api/logout'
        _controller: 'Api::logout'
    requirements:
      ics: \d+
      calendar: \d+
      day: \d+
      month: \d+
      year: \d+
